name: williamhaighdesign
favicon: null
layout_spectrum: 0.9482043846510351
typography_spectrum: 0.09439713577739894
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.12823646166361868
  lightness: 0.10056752152740955
  saturation: 0.0495122317224741
  rhythmicContrast: 0.5038677563425153
purpose: []
